services:
  bot:
    build: .
    container_name: finance-bot
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: python app/bot.py

  db:
    image: mysql:8.0
    container_name: finance-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
